//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.24 at 04:41:14 PM SGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.loc.gov/MARC21/slim", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package my.com.myriadeas.integral.cataloguing.marc.model;
